stages:
  - test

.unit-test: &unit
  stage: test
  variables:
    #TOX_SKIP_ENV: "py37.*"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  script:
    - tox --skip-missing-interpreters -a auto -- -qrf
  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install -e .
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

test-python36:
  <<: *unit
  image: python:3.6
  variables:
     TOXENV: py36

test-python37:
  <<: *unit
  image: python:3.7
  variables:

test-python38:
  <<: *unit
  image: python:3.8
  variables:
     TOXENV: py38    

test-python39:
  <<: *unit
  image: python:3.9-rc

test-pypy3:
  <<: *unit
  image: pypy:3
  variables:
     TOXENV: pypy3
